### ISSUE TITLE
how to record the whole test operation as video 

### ISSUE THREAD

**Issue by wanghaisheng** [Rink9/csv-importer-visual-automation#1]

**Comment by Rink9** [comment]
@wanghaisheng There is no way to record whole operation as video right now for this project. But you can just record operations devices default video recorder.

**Comment by wanghaisheng** [comment]
ou can just record operations devices default video recorder.?
you mean screen recording tools third party instead of playright embedded

**Comment by Rink9** [comment]
@wanghaisheng Exactly. You are right.
